# Generated by Django 3.1.1 on 2020-09-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200928_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='completed',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='content',
            new_name='label',
        ),
    ]
