# Generated by Django 3.1.1 on 2020-09-30 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200930_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='done',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='label',
            new_name='title',
        ),
    ]
